# Generated by Django 5.0.6 on 2025-07-22 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_ciclo_codigo_ciclo_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='duracion_unidad',
            field=models.PositiveIntegerField(blank=True, help_text='Número de unidades/semanas (define tú el criterio)', null=True, verbose_name='Duración de la unidad'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='horas_programadas',
            field=models.PositiveIntegerField(blank=True, help_text='Total de horas planificadas', null=True, verbose_name='Horas programadas'),
        ),
    ]
