# Generated by Django 5.0.6 on 2025-07-23 00:05

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_asignatura_duracion_unidad_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignatura',
            options={'ordering': ['nombre'], 'verbose_name': 'Asignatura', 'verbose_name_plural': 'Asignaturas'},
        ),
        migrations.RemoveField(
            model_name='asignatura',
            name='duracion_unidad',
        ),
        migrations.AddField(
            model_name='asignatura',
            name='codigo',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, unique=True, verbose_name='Código'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asignatura',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asignatura',
            name='is_activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='unidades_totales',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Número de unidades del sílabo', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Unidades totales'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='horas_programadas',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Total de horas planificadas', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Horas programadas'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='nombre',
            field=models.CharField(max_length=120),
        ),
        migrations.AddIndex(
            model_name='asignatura',
            index=models.Index(fields=['periodo', 'nombre'], name='tareas_asig_periodo_6300da_idx'),
        ),
        migrations.AddConstraint(
            model_name='asignatura',
            constraint=models.UniqueConstraint(fields=('periodo', 'codigo'), name='uniq_asignatura_codigo_periodo'),
        ),
    ]
